// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceFolders(arg1) {
  return window['go']['main']['App']['GetDeviceFolders'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetFolderContents(arg1, arg2) {
  return window['go']['main']['App']['GetFolderContents'](arg1, arg2);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetHTTPSDeviceFolders(arg1) {
  return window['go']['main']['App']['GetHTTPSDeviceFolders'](arg1);
}

export function GetHTTPSDevices() {
  return window['go']['main']['App']['GetHTTPSDevices']();
}

export function GetHTTPSFolderContents(arg1, arg2) {
  return window['go']['main']['App']['GetHTTPSFolderContents'](arg1, arg2);
}

export function GetHTTPSSyncthingConfigDevices() {
  return window['go']['main']['App']['GetHTTPSSyncthingConfigDevices']();
}

export function GetHTTPSSyncthingDeviceID(arg1) {
  return window['go']['main']['App']['GetHTTPSSyncthingDeviceID'](arg1);
}

export function GetHTTPSSyncthingDiscovery() {
  return window['go']['main']['App']['GetHTTPSSyncthingDiscovery']();
}

export function GetHTTPSSyncthingEvents(arg1, arg2) {
  return window['go']['main']['App']['GetHTTPSSyncthingEvents'](arg1, arg2);
}

export function GetHTTPSWifiInfo() {
  return window['go']['main']['App']['GetHTTPSWifiInfo']();
}

export function GetSyncthingStatus() {
  return window['go']['main']['App']['GetSyncthingStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PostHTTPSAddDevice(arg1) {
  return window['go']['main']['App']['PostHTTPSAddDevice'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartSyncthing() {
  return window['go']['main']['App']['StartSyncthing']();
}

export function StopSyncthing() {
  return window['go']['main']['App']['StopSyncthing']();
}
